[package]
name = "ingredient_heist"
edition = "2024"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/devnet" }

[addresses]
ingredient_heist = "0x0"
