[package]
name = "aa_account"
edition = "2024"

[dependencies]
Iota = { git = "https://github.com/iotaledger/iota.git", subdir = "crates/iota-framework/packages/iota-framework", rev = "framework/devnet" }
public_key_authentication = { local = "../../../lib/public_key_authentication" }

[addresses]
aa_account = "0x0"
